# SHORTS BOT CONFIG
# Credentials come from GitHub Secrets - do not put them here

source_channels:
  - id: "UCk4Rd9-a002y2wzTIeOq9zQ"
    name: "japn.channel"
  - id: "UC2TovL8uv6fCPrLdzoQbtUQ"
    name: "asianfoodtotaste"
  - id: "UCRPYE7w_6oYDxvpqQ2MR02g"
    name: "or__and_food"

shorts_per_day: 1
upload_delay_seconds: 30
check_interval_hours: 6
